// Package sync writes a generated context block into the CLAUDE.md of every repository a
// vault note claims, so an agent working inside a repo knows which note describes it
// without needing the vault open.
//
// The block sits between markers and is replaced in place, so anything written around it
// survives. The interesting problem here is not writing the block, it is deciding which
// repositories are ours to write into at all: see ownedBy.
package sync

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/joeykokinda/aimem/internal/config"
	"github.com/joeykokinda/aimem/internal/vault"
)

const (
	beginMarker = "<!-- aimem:begin generated by aimem, do not edit inside -->"
	endMarker   = "<!-- aimem:end -->"
)

// markerPairs are the begin/end pairs a generated block may be delimited by, newest
// first. Older pairs are recognized so an upgrade replaces the existing block rather
// than appending a second one beside it. Each pair must be matched as a pair: matching a
// legacy begin against the current end finds nothing and silently duplicates.
var markerPairs = [][2]string{
	{beginMarker, endMarker},
	{"<!-- obby:begin", "<!-- obby:end -->"},
}

// Outcome reports what a sync did, per repository.
type Outcome struct {
	Written []string
	Skipped []string
}

// Run refreshes the context block in each mapped repository.
func Run(settings *config.Config, notes []*vault.Note, dryRun bool) (*Outcome, error) {
	outcome := &Outcome{}
	if !settings.SyncEnabled {
		return outcome, nil
	}
	for _, note := range notes {
		if note.Repo == "" || note.Status == "dead" {
			continue
		}
		info, err := os.Stat(note.Repo)
		if err != nil || !info.IsDir() {
			continue
		}
		reason := skipReason(settings, note.Repo)
		if reason != "" {
			outcome.Skipped = append(outcome.Skipped, fmt.Sprintf("%s (%s)", note.Repo, reason))
			continue
		}
		if dryRun {
			outcome.Written = append(outcome.Written, filepath.Join(note.Repo, "CLAUDE.md"))
			continue
		}
		path, err := writeBlock(settings, note)
		if err != nil {
			return outcome, err
		}
		outcome.Written = append(outcome.Written, path)
	}
	return outcome, nil
}

// skipReason decides whether a repository is ours to write into. The previous version of
// this was a hardcoded list of absolute paths, which is inert on any other machine: the
// guard against editing someone else's CLAUDE.md silently stopped guarding the moment
// the directory layout changed. Ownership is derived from the git remote instead, which
// travels correctly.
func skipReason(settings *config.Config, repo string) string {
	for _, candidate := range settings.SyncSkip {
		if matched, _ := filepath.Match(candidate, repo); matched || candidate == repo {
			return "listed in sync.skip"
		}
	}
	if len(settings.SyncOwners) == 0 {
		return ""
	}
	remote := originRemote(repo)
	if remote == "" {
		// A repository with no remote is local-only work, which cannot be someone else's:
		// a checkout of another person's project always carries the remote it came from.
		// Treating "no remote" as foreign would skip exactly the scratch repos that most
		// need a pointer back to their vault note.
		return ""
	}
	if ownedBy(remote, settings.SyncOwners) {
		return ""
	}
	return fmt.Sprintf("remote %s is not owned by %s", remote, strings.Join(settings.SyncOwners, "/"))
}

func originRemote(repo string) string {
	command := exec.Command("git", "-C", repo, "remote", "get-url", "origin")
	output, err := command.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(output))
}

// ownedBy matches an owner against the owner segment of a remote URL, handling both
// git@host:owner/repo.git and https://host/owner/repo.git.
func ownedBy(remote string, owners []string) bool {
	normalized := remote
	if cut := strings.Index(normalized, "://"); cut >= 0 {
		normalized = normalized[cut+3:]
		if at := strings.Index(normalized, "@"); at >= 0 {
			normalized = normalized[at+1:]
		}
	}
	normalized = strings.Replace(normalized, ":", "/", 1)
	normalized = strings.TrimSuffix(normalized, ".git")

	parts := strings.Split(normalized, "/")
	if len(parts) < 2 {
		return false
	}
	owner := parts[len(parts)-2]
	for _, candidate := range owners {
		if strings.EqualFold(owner, candidate) {
			return true
		}
	}
	return false
}

func writeBlock(settings *config.Config, note *vault.Note) (string, error) {
	target := filepath.Join(note.Repo, "CLAUDE.md")
	block := renderBlock(settings, note)

	existing, err := os.ReadFile(target)
	if os.IsNotExist(err) {
		return target, os.WriteFile(target, []byte(block+"\n"), 0o644)
	}
	if err != nil {
		return target, err
	}

	// Strip every generated block, of any marker vintage, before inserting the new one.
	// Replacing only the first match leaves a stale block behind whenever a rename put
	// two vintages in the same file, and that stale copy is the one that contradicts.
	stripped, insertAt := stripBlocks(string(existing))

	var rebuilt string
	if insertAt >= 0 {
		rebuilt = stripped[:insertAt] + block + stripped[insertAt:]
	} else {
		rebuilt = strings.TrimRight(stripped, "\n") + "\n\n" + block + "\n"
	}
	return target, os.WriteFile(target, []byte(strings.TrimRight(rebuilt, "\n")+"\n"), 0o644)
}

// stripBlocks removes every generated block and reports where the first one started, so
// the replacement lands in the same place rather than jumping to the end of the file.
func stripBlocks(text string) (string, int) {
	insertAt := -1
	for {
		found := false
		for _, pair := range markerPairs {
			start := strings.Index(text, pair[0])
			if start < 0 {
				continue
			}
			stop := strings.Index(text[start:], pair[1])
			if stop < 0 {
				continue
			}
			end := start + stop + len(pair[1])
			// Absorb the blank line a previous append left behind, so repeated runs do
			// not accumulate vertical space.
			for end < len(text) && text[end] == '\n' {
				end++
			}
			if insertAt < 0 || start < insertAt {
				insertAt = start
			}
			text = text[:start] + text[end:]
			found = true
			break
		}
		if !found {
			return text, insertAt
		}
	}
}

func renderBlock(settings *config.Config, note *vault.Note) string {
	versioned := "tracked in git"
	if _, err := os.Stat(filepath.Join(note.Repo, ".git")); err != nil {
		versioned = "**not under version control**"
	}
	status := note.Status
	if status == "" {
		status = "unset"
	}

	var out strings.Builder
	out.WriteString(beginMarker + "\n")
	out.WriteString(fmt.Sprintf("## %s vault context\n\n", settings.Name))
	out.WriteString(fmt.Sprintf("This repo is described by `%s` in the vault at `%s`.\n\n", note.Path, settings.Root))
	out.WriteString(fmt.Sprintf("- **Note:** %s\n", note.Title))
	out.WriteString(fmt.Sprintf("- **Status in vault:** %s\n", status))
	out.WriteString(fmt.Sprintf("- **Version control:** %s\n\n", versioned))
	out.WriteString("Read the vault note before asking what this project is or how it fits together.\n")
	out.WriteString("`aimem project` prints it; `aimem context` prints the full cross-project index.\n\n")
	out.WriteString("If you change what this project *is* (scope, stack, status, whether it is still\n")
	out.WriteString("alive), update the vault note too, then run `aimem refresh`.\n\n")
	if len(settings.Private) > 0 {
		quoted := make([]string, 0, len(settings.Private))
		for _, folder := range settings.Private {
			quoted = append(quoted, "`"+folder+"`")
		}
		out.WriteString(fmt.Sprintf("Vault folders %s are private. Do not read them.\n", strings.Join(quoted, ", ")))
	}
	out.WriteString(endMarker)
	return out.String()
}
